server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ANSHULI50/demo-microservices
          #username:  
          #password: 
          
                 